### ISSUE TITLE
Error when a name is available

### ISSUE THREAD

**Issue by amitness** [danishprakash/pip-name#1]
When the name is not present, the script runs as expected. But, when a name is available, I'm getting this error:

![image](https://user-images.githubusercontent.com/8587189/48301937-6cfafb00-e51d-11e8-83b0-bd920f56147f.png)

**Comment by danishprakash** [comment]
Thanks for bringing this up @amitness, this was an issue related to unicode strings. Since python3 has by default strings encoded as unicode, It did not occur to me that a handling condition was required for python2.
